### ISSUE TITLE
스프레드 시트 field id 입력을 직접 입력을 받기 보다는 주소 전체를 입력 받아 파싱하는 방안

### ISSUE THREAD

**Issue by seul-bi-keem** [ssk0dev/android-string-table#22]
사용자 입장에서 field id 라는게 생소할 수도 있고 
굳이 찾아서 거기만 복붙하는거보단
주소 전체 입력해버리는게 쉬울거 같습니다.

**Comment by deviankim** [comment]
좋은 방법입니다.
문서/시트 따로 받을 필요 없이 전체주소 하나면 땡이네요.

**Comment by seul-bi-keem** [comment]
입력받은 주소에서 spreadSheetID와 sheetID를 찾을 수 없는 경우엔 어떻게 해야하는지 방안 생각해보기
